version: '3.8'

services:
  rest-app:
    build: ./rest-client/.
    restart: always
    # env_file: ./.env
    ports:
      - 8090:8090
    stdin_open: true
    tty: true
  web-app:
    build: cloud-console/.
    restart: always
    ports:
      - 8080:80
    stdin_open: true
    tty: true