version: '3.8'

services:
  cloud-api:
    build: ./cloud-api/.
    restart: always
    # env_file: ./.env
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
  cloud-web:
    build: ./cloud-web/.
    restart: always
    ports:
      - 3000:80
    stdin_open: true
    tty: true